services:
  mysql:
    image: mysql:latest
    container_name: mysql-server
    restart: on-failure # reiniciar el contenedor si falla pero no cuando se detiene manualmente o se reinicia el servicio de docker
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pruebas
      MYSQL_USER: rdev
      MYSQL_PASSWORD: rdev
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
