services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Ron@ld1234"
      ACCEPT_EULA: "Y"
    restart: on-failure # reiniciar el contenedor si falla pero no cuando se detiene manualmente o se reinicia el servicio de docker
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
