services:
  postgres:
    image: postgres:latest
    container_name: postgres-server
    restart: always
    environment:
      POSTGRES_USER: rdev
      POSTGRES_PASSWORD: rdev
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
